spring:
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    username: user
    password: 1234
    url:  ${SPRING_R2DBC_URL:r2dbc:mysql://localhost:3306/order}
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: ${SPRING_FLYWAY_URL:jdbc:mysql://localhost:3306/order}
  cloud:
    config:
      uri: ${CONFIG_SERVICE_URL:http://localhost:8888}
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
    function:
      definition: dispatchOrder
    stream:
      bindings:
        dispatchOrder-in-0:
          destination: order-dispatched
          group: {spring.application.name}
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 1234
    connection-timeout: 5s

server:
  port: 9002
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

polar:
  catalog-service-uri: ${CATALOG_SERVICE_URL:http://localhost:9001}